# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  serve:
    deps: ["build"]
    cmds:
      - ./cert-manager serve --daemon
    silent: true
  default:
    deps: ["build"]
    cmds:
      - ./cert-manager serve
    silent: true
  build:
    cmds:
      - go build -o cert-manager ./cmd/cert-manager/
    silent: true
